portKiller:
  ports:
    # http ports
    - 8080
    - 8081
    - 8082
    - 8083
    - 8084
    - 8085
    - 8086
    - 8087
    - 8088
    - 8089
    - 8090
    - 8091
    - 8092
    - 8093
    - 8094
    - 8095
    - 8096

    # JMX ports
    - 1099
    - 1100
    - 1101
    - 1102
    - 1103
    - 1104
    - 1105
    - 1106
    - 1107
    - 1108
    - 1109
    - 1110
    - 1111
    - 1112
    - 1113
    - 1114
    - 1115

  onlyListening: true
  forceKill: true
  dryRun: false
  # dryRun: true
